## Beauitiful Plotly Charts & Analyzing the Android App Store

In [23]:
import pandas as pd

In [24]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

read data set

In [25]:
df = pd.read_csv("apps.csv")

Data Cleaning

In [26]:
df.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social,"July 28, 2017",4.1 and up
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.00,0,Paid,$2.99,Everyone,Education,"April 15, 2016",3.0 and up
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.50,0,Paid,$1.49,Everyone,Personalization,"July 11, 2018",4.2 and up
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.00,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device
4,CX Network,BUSINESS,NaN,0,10.00,0,Free,0,Everyone,Business,"August 6, 2018",4.1 and up

In [27]:
df.shape

(10841, 12)

In [28]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='object')

In [29]:
df.sample(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
7578,Video Status,VIDEO_PLAYERS,4.30,6685,4.00,"1,000,000",Free,0,Everyone,Video Players & Editors,"August 2, 2018",4.1 and up
7529,Fresh EBT - Food Stamp Balance,FINANCE,4.50,19870,7.40,"1,000,000",Free,0,Everyone,Finance,"July 24, 2018",4.0.3 and up
3459,Ad-free Triangle Solver,FAMILY,4.50,118,24.00,"10,000",Free,0,Everyone,Education,"August 20, 2015",4.2 and up
9701,"Yahoo! transit guide free timetable, operation...",MAPS_AND_NAVIGATION,4.40,104800,22.00,"10,000,000",Free,0,Everyone,Maps & Navigation,"July 26, 2018",4.0 and up
1853,FG On-The-Go,TOOLS,4.90,55,25.00,"1,000",Free,0,Everyone,Tools,"June 29, 2018",4.1 and up

find and remove NaN  Value ratings

In [30]:
df["Rating"].isna().sum()

1474

In [31]:
df[df["Rating"].isna()]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social,"July 28, 2017",4.1 and up
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.00,0,Paid,$2.99,Everyone,Education,"April 15, 2016",3.0 and up
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.50,0,Paid,$1.49,Everyone,Personalization,"July 11, 2018",4.2 and up
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.00,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device
4,CX Network,BUSINESS,NaN,0,10.00,0,Free,0,Everyone,Business,"August 6, 2018",4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
5840,Em Fuga Brasil,FAMILY,NaN,1317,60.00,"100,000",Free,0,Everyone,Simulation,"April 22, 2018",4.1 and up
5862,Voice Tables - no internet,PARENTING,NaN,970,71.00,"100,000",Free,0,Everyone,Parenting,"May 28, 2018",4.0.3 and up
6141,Young Speeches,LIBRARIES_AND_DEMO,NaN,2221,2.40,"500,000",Free,0,Everyone,Libraries & Demo,"January 8, 2017",2.3 and up
7035,SD card backup,TOOLS,NaN,142,3.40,"1,000,000",Free,0,Everyone,Tools,"March 27, 2017",Varies with device
7175,Android TV Remote Service,TOOLS,NaN,1,3.70,"1,000,000",Free,0,Everyone,Tools,"January 17, 2018",7.0 and up

In [32]:
df.dropna(subset=["Rating"], inplace=True)

In [33]:
df["Rating"].isna().sum()

0

find and remove duplicates

In [34]:
df.duplicated().sum()

474

In [35]:
df[df.duplicated()]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
946,420 BZ Budeze Delivery,MEDICAL,5.00,2,11.00,100,Free,0,Mature 17+,Medical,"June 6, 2018",4.1 and up
1133,MouseMingle,DATING,2.70,3,3.90,100,Free,0,Mature 17+,Dating,"July 17, 2018",4.4 and up
1196,"Cardiac diagnosis (heart rate, arrhythmia)",MEDICAL,4.40,8,6.50,100,Paid,$12.99,Everyone,Medical,"July 25, 2018",3.0 and up
1231,Sway Medical,MEDICAL,5.00,3,22.00,100,Free,0,Everyone,Medical,"July 25, 2018",5.0 and up
1247,Chat Kids - Chat Room For Kids,DATING,4.70,6,4.90,100,Free,0,Mature 17+,Dating,"July 24, 2018",4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10802,Skype - free IM & video calls,COMMUNICATION,4.10,10484169,3.50,"1,000,000,000",Free,0,Everyone,Communication,"August 3, 2018",Varies with device
10809,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social,"July 31, 2018",Varies with device
10826,Google Drive,PRODUCTIVITY,4.40,2731211,4.00,"1,000,000,000",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device
10832,Google News,NEWS_AND_MAGAZINES,3.90,877635,13.00,"1,000,000,000",Free,0,Teen,News & Magazines,"August 1, 2018",4.4 and up
10839,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up

In [36]:
df.drop_duplicates(inplace=True)

In [37]:
df.duplicated().sum()

0

find highest rated apps

In [38]:
df["Rating"].max()

5.0

find 5 largest apps in terms of size

In [2]:
import plotly,express as px

ModuleNotFoundError: No module named 'plotly'