## Data Science with Pandas

On this day as im failiar with pandas and already have a seted up envirment ill just to straight to start working

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.1'

Upload and read the csv file

In [3]:
import pandas as pd

df = pd.read_csv("salaries_by_college_major.csv")

df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

Preliminary Data Exploration

lokking at the data set

In [4]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

first fove rows

In [5]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

number of rows and columnbs

In [6]:
df.shape

(51, 6)

column names

In [7]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

info of the data frame

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Undergraduate Major                51 non-null     object
 1   Starting Median Salary             50 non-null     float64
 2   Mid-Career Median Salary           50 non-null     float64
 3   Mid-Career 10th Percentile Salary  50 non-null     float64
 4   Mid-Career 90th Percentile Salary  50 non-null     float64
 5   Group                              50 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.5+ KB

statistical summary

In [9]:
df.describe()

,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
count,50.000000,50.00000,50.000000,50.000000
mean,44310.000000,74786.00000,43408.000000,142766.000000
std,9360.866217,16088.40386,12000.779567,27851.249267
min,34000.000000,52000.00000,26700.000000,96400.000000
25%,37050.000000,60825.00000,34825.000000,124250.000000
50%,40850.000000,72000.00000,39400.000000,145500.000000
75%,49875.000000,88750.00000,49850.000000,161750.000000
max,74300.000000,107000.00000,71900.000000,210000.000000

for missing values

In [10]:
df.isna().sum()

Undergraduate Major                  0
Starting Median Salary               1
Mid-Career Median Salary             1
Mid-Career 10th Percentile Salary    1
Mid-Career 90th Percentile Salary    1
Group                                1
dtype: int64

can remove rows containing missing values

In [11]:
clean_df = df.dropna()

Access Columns and Individual Cells

get a column

In [12]:
df["Undergraduate Major"]

0                               Accounting
1                    Aerospace Engineering
2                              Agriculture
3                             Anthropology
4                             Architecture
5                              Art History
6                                  Biology
7                      Business Management
8                     Chemical Engineering
9                                Chemistry
10                       Civil Engineering
11                          Communications
12                    Computer Engineering
13                        Computer Science
14                            Construction
15                        Criminal Justice
16                                   Drama
17                               Economics
18                               Education
19                  Electrical Engineering
20                                 English
21                                    Film
22                                 Finance
23                                Forestry
24                               Geography
25                                 Geology
26                          Graphic Design
27              Health Care Administration
28                                 History
29                   Hospitality & Tourism
30                  Industrial Engineering
31             Information Technology (IT)
32                         Interior Design
33                 International Relations
34                              Journalism
35    Management Information Systems (MIS)
36                               Marketing
37                                    Math
38                  Mechanical Engineering
39                                   Music
40                                 Nursing
41                               Nutrition
42                              Philosophy
43                     Physician Assistant
44                                 Physics
45                       Political Science
46                              Psychology
47                                Religion
48                               Sociology
49                                 Spanish
50                   Source: PayScale Inc.
Name: Undergraduate Major, dtype: object

starting salary

In [13]:
df["Starting Median Salary"]

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
50        NaN
Name: Starting Median Salary, dtype: float64

mid career salary

In [14]:
df["Mid-Career Median Salary"]

0      77100.0
1     101000.0
2      71900.0
3      61500.0
4      76800.0
5      64900.0
6      64800.0
7      72100.0
8     107000.0
9      79900.0
10     90500.0
11     70000.0
12    105000.0
13     95500.0
14     88900.0
15     56300.0
16     56900.0
17     98600.0
18     52000.0
19    103000.0
20     64700.0
21     68500.0
22     88300.0
23     62600.0
24     65500.0
25     79500.0
26     59800.0
27     60600.0
28     71000.0
29     57500.0
30     94700.0
31     74800.0
32     53200.0
33     80900.0
34     66700.0
35     82300.0
36     79600.0
37     92400.0
38     93600.0
39     55000.0
40     67000.0
41     55300.0
42     81200.0
43     91700.0
44     97300.0
45     78200.0
46     60400.0
47     52000.0
48     58200.0
49     53100.0
50         NaN
Name: Mid-Career Median Salary, dtype: float64

get an idividual cell

In [15]:
df.iloc[0]

Undergraduate Major                  Accounting
Starting Median Salary                  46000.0
Mid-Career Median Salary                77100.0
Mid-Career 10th Percentile Salary       42200.0
Mid-Career 90th Percentile Salary      152000.0
Group                                  Business
Name: 0, dtype: object

first row and  column

In [16]:
df.iloc[0, 0]

'Accounting'

first row second column

In [17]:
df["Undergraduate Major"].iloc[0]

'Accounting'

Highest and Lowest Earning Degrees

highest starting salary

In [18]:
df["Starting Median Salary"].max()

74300.0

what about the major

In [19]:
df[df["Starting Median Salary"] == df["Starting Median Salary"].max()]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM

lowest starting salary

In [20]:
df[df["Starting Median Salary"] == df["Starting Median Salary"].min()]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

highest mid career salary

In [21]:
df[df["Mid-Career Median Salary"] == df["Mid-Career Median Salary"].max()]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM

lowest mid carrer salary

In [22]:
df[df["Mid-Career Median Salary"] == df["Mid-Career Median Salary"].min()]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS

Sorting Values & Adding Columns

highest starting salary

In [23]:
df.sort_values("Starting Median Salary", ascending=False).head(10)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM

lowest

In [24]:
df.sort_values("Starting Median Salary").head(10)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
39,Music,35900.0,55000.0,26700.0,134000.0,HASS

create a new column

In [25]:
df["Salary Difference"] = (
    df["Mid-Career Median Salary"]
    - df["Starting Median Salary"]
)

now read

In [26]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Salary Difference
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business,31100.0
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM,43300.0
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business,29300.0
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS,24700.0
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business,35200.0

Degrees with the Highest Potential

In [27]:
df.sort_values("Salary Difference", ascending=False).head(10)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Salary Difference
17,Economics,50100.0,98600.0,50600.0,210000.0,Business,48500.0
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM,47000.0
37,Math,45400.0,92400.0,45200.0,183000.0,STEM,47000.0
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM,43800.0
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM,43600.0
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM,43300.0
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM,42100.0
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS,41300.0
22,Finance,47900.0,88300.0,47200.0,195000.0,Business,40400.0
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS,40000.0

calculate the percentage increase

In [28]:
df["Salary Increase %"] = (
    df["Salary Difference"] /
    df["Starting Median Salary"]
) * 100

In [29]:
df.sort_values("Salary Increase %", ascending=False).head(10)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Salary Difference,Salary Increase %
37,Math,45400.0,92400.0,45200.0,183000.0,STEM,47000.0,103.524229
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS,41300.0,103.508772
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS,40000.0,97.799511
17,Economics,50100.0,98600.0,50600.0,210000.0,Business,48500.0,96.806387
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business,38800.0,95.098039
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM,47000.0,93.439364
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS,37400.0,91.666667
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM,37300.0,87.558685
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS,31100.0,87.359551
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business,35200.0,84.615385

Grouping and Pivoting

columun representing major category

In [ ]:
df.groupby("Major_category")["Mid-Career Median Salary"].mean()

In [ ]:
df.groupby("Major_category")["Mid-Career Median Salary"].mean().sort_values(
    ascending=False
)

pivot table

In [ ]:
pd.pivot_table(
    df,
    values="Mid-Career Median Salary",
    index="Major_category",
    aggfunc="mean"
)