## Data Visualization with matplotlib: Programming Languages

first step on this day is to download and open the starter notebook

In [32]:
import pandas as pd

df = pd.read_csv("QueryResults.csv")

df.head()

                     m     TagName  Unnamed: 2
0  2008-07-01 00:00:00          c#           3
1  2008-08-01 00:00:00    assembly           8
2  2008-08-01 00:00:00  javascript         162
3  2008-08-01 00:00:00           c          85
4  2008-08-01 00:00:00      python         124

then check the data set

In [33]:
df.shape

(1991, 3)

In [34]:
df.columns

Index(['m', 'TagName', 'Unnamed: 2'], dtype='object')

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1991 entries, 0 to 1990
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   m           1991 non-null   object
 1   TagName     1991 non-null   object
 2   Unnamed: 2  1991 non-null   int64
dtypes: int64(1), object(2)
memory usage: 46.8+ KB

In [36]:
df.describe()

         Unnamed: 2
count   1991.000000
mean    5069.401306
std     6065.055196
min        1.000000
25%      426.500000
50%     2472.000000
75%     8163.000000
max    34478.000000

Data Expolratioin

In [37]:
df.head()

                     m     TagName  Unnamed: 2
0  2008-07-01 00:00:00          c#           3
1  2008-08-01 00:00:00    assembly           8
2  2008-08-01 00:00:00  javascript         162
3  2008-08-01 00:00:00           c          85
4  2008-08-01 00:00:00      python         124

check missing values

In [38]:
df.isna().sum()

m             0
TagName       0
Unnamed: 2    0
dtype: int64

chech data types

In [39]:
df.dtypes

m             object
TagName       object
Unnamed: 2     int64
dtype: object

Analysis by Programming Language

In [40]:
df["TagName"].unique()

array(['c#', 'assembly', 'javascript', 'c', 'python', 'perl', 'c++',
       'java', 'delphi', 'ruby', 'php', 'r', 'swift', 'go'], dtype=object)

after viewing this we can filter of a particular language

In [41]:
df[df["TagName"] == "Python"]

Empty DataFrame
Columns: [m, TagName, Unnamed: 2]
Index: []

In [42]:
df[df["TagName"] == "Java"]

Empty DataFrame
Columns: [m, TagName, Unnamed: 2]
Index: []

In [43]:
df[df["TagName"] == "JavaScript"]

Empty DataFrame
Columns: [m, TagName, Unnamed: 2]
Index: []

Data Cleaning — Working With Timestamps

supper the date column is m we can convert it, into proper pandas datetime

In [44]:
df["m"] = pd.to_datetime(df["m"])

check

In [45]:
df.dtypes

m             datetime64[ns]
TagName               object
Unnamed: 2             int64
dtype: object

Pivoting DataFrames

we chanje to a new readable data frame

In [46]:
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
df = pd.read_csv("QueryResults.csv")

In [48]:
df["m"] = pd.to_datetime(df["m"])

In [49]:
print(df.columns)

Index(['m', 'TagName', 'Unnamed: 2'], dtype='object')

In [50]:
print(df.head())

           m     TagName  Unnamed: 2
0 2008-07-01          c#           3
1 2008-08-01    assembly           8
2 2008-08-01  javascript         162
3 2008-08-01           c          85
4 2008-08-01      python         124

In [ ]:
pivoted_df = df.pivot(
    index="m",
    columns="TagName",
    values="Count"
)

In [ ]:
pivoted_df.head()

the new data frames

In [ ]:
pivoted_df.shape

In [ ]:
pivoted_df.columns

Data Visualisation with Matplotlib

In [ ]:
pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\my pc\miniconda3\envs\arewads\lib\site-packages (3.8.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: contourpy>=1.0.1 in c:\users\my pc\miniconda3\envs\arewads\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\my pc\miniconda3\envs\arewads\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\my pc\miniconda3\envs\arewads\lib\site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\my pc\miniconda3\envs\arewads\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy<2,>=1.21 in c:\users\my pc\miniconda3\envs\arewads\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\my pc\appdata\roaming\python\python310\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\my pc\miniconda3\envs\arewads\lib\site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\my pc\miniconda3\envs\arewads\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\my pc\appdata\roaming\python\python310\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\my pc\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

In [52]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(
    pivoted_df.index,
    pivoted_df["python"]
)

plt.show()

add another label

In [ ]:
plt.figure(figsize=(12, 6))

plt.plot(
    pivoted_df.index,
    pivoted_df["python"]
)

plt.xlabel("Year")
plt.ylabel("Number of Questions")
plt.title("Popularity of Python on Stack Overflow")

plt.show()

Multi-Line Charts

we can compare multiple programming languages

In [ ]:
plt.figure(figsize=(12, 6))

plt.plot(
    pivoted_df.index,
    pivoted_df["python"],
    label="Python"
)

plt.plot(
    pivoted_df.index,
    pivoted_df["java"],
    label="Java"
)

plt.plot(
    pivoted_df.index,
    pivoted_df["javascript"],
    label="JavaScript"
)

plt.legend()

plt.xlabel("Year")
plt.ylabel("Number of Questions")
plt.title("Programming Language Popularity")

plt.show()